### PR TITLE
Moved fiducial tf publishing to aruco_detect node

### PR DESCRIPTION
**Pull request by jim-v**
Related to https://github.com/UbiquityRobotics/move_basic/pull/52

### CODE REVIEW

**Comment by rohbotics** [comment]
I think that the TF publishing needs to have a parameter that allows you to disable it.

A Boolean `publish_fiducial_tf` with a default of true would make sense.

**Review by rohbotics — APPROVED** [review]
Looks good to me.

Before merging, I want Vid (@MoffKalast) to take a look at it since it will effect some of his code. Vid is part of the team in Slovenia.

**Comment by MoffKalast** [comment]
It was indeed somewhat annoying that each node using fiducials needed to make its own tf publisher for debug, so yeah a pretty good change imo.

**Comment by rohbotics** [comment]
@jim-v Looks like Travis is broken, I am going to manually override that check and merge this.

**Pull request merged**
