### PR TITLE
Publish one set of fiducial_vertices per image. 

### LINKED ISSUE #47: aruco_detect should publish empty fiducial_vertices
When there are no markers, we should publish an empty fiducial_vertices

### PR DESCRIPTION
**Pull request by jim-v**
Fixes #47

### CODE REVIEW

**Review by rohbotics — COMMENTED** [review]
Does it make sense to use this in the fiducial message instead of a bunch of floats
http://docs.ros.org/jade/api/sensor_msgs/html/msg/RegionOfInterest.html

**Comment by jim-v** [comment]
The region of interest only allows rectangles that are aligned with the axes to be specified.  Four points can specify a rectangle or trapezoid in an arbitrary rotation.  Also, we need floats for sub-pixel resolution..

**Review by rohbotics — APPROVED** [review]

**Comment by rohbotics** [comment]
That makes sense, I was wondering why we made our own message.

**Comment by jim-v** [comment]
Thanks for the review, @rohbotics.  It's great that you are looking for ways to clean up the code.

**Pull request merged**
