### PR TITLE
Add service call to add a fiducial to the map

### PR DESCRIPTION
**Pull request by jim-v**
Add a service call for adding a fiducial to the map.  It will store the fiducial_id and then calls to `handleAddFIducial()` will attempt to add it.   The request to add the fiducial is ignored if it already in the map.   If the position of the robot (tf from `map` to `base_footprint`) is known, then the fiducial's pose is calculated such that the robot's current pose will be maintained.   If it is not known, then the fiducial's pose is calculated such that the robot is at the origin (similar to what is auto init does).

### CODE REVIEW

**Comment by rohbotics** [comment]
The code itself seems sound, but I am questioning the usecase for this.

You would have to call the add fiducial pretty early in the launch to prevent auto-init from happening first, other wise you would end up with 2 fiducials competing to be at the 'origin'.

**Comment by jim-v** [comment]
> The code itself seems sound, but I am questioning the usecase for this.
> 
> You would have to call the add fiducial pretty early in the launch to prevent auto-init from happening first, other wise you would end up with 2 fiducials competing to be at the 'origin'.

If the robot's pose is known, then the new fiducial is added such that it supports that pose.  This could be used to support a more sparse placement of fiducials.  Also, if the robot's pose is not known and we do end up with a map with more than one fiducial being the 'origin', it won't matter in this particular use case since fiducials other than the one being used are ignored.  I think the risks are mitigated by the fact that the service call has to be explicitly invoked.

**Comment by rohbotics** [comment]
Maybe I am not understanding something here.

If I am navigating in an existing map with fiducials 1 2 3 4 in view, and then I call the add fiducial service for fid5 what will happen? What about when I then drive to a location where fid5 is visible?

**Comment by jim-v** [comment]
> Maybe I am not understanding something here.
> 
> If I am navigating in an existing map with fiducials 1 2 3 4 in view, and then I call the add fiducial service for fid5 what will happen? What about when I then drive to a location where fid5 is visible?

The next time that fid5 is visible it will be added to the map, using the robot's position to calculate its pose if there are no other fiducials in view.  If you need to discuss this further, I'm happy to talk on the phone.

**Review by rohbotics — APPROVED** [review]

**Comment by rohbotics** [comment]
Ah, ok I got it. Thanks!

Rohan

**Pull request merged**
