### PR TITLE
Fix multiplication order bug in autoInit()

### PR DESCRIPTION
**Pull request by jim-v**
It now works correctly.  TODO: add a test.

### CODE REVIEW

**Review by rohbotics — COMMENTED** [review]
:+1: Let me know when you add that test.

**Comment by jim-v** [comment]
Test added

**Comment by jim-v** [comment]
@rohbotics Don't review this yet, there's something not right

**Comment by jim-v** [comment]
@rohbotics I figured out it was an unrelated issue.  Please review when you have time.

**Review by rohbotics — APPROVED** [review]
Thanks for fixing this bug and adding a regression test as well.

**Pull request merged**
