### PR TITLE
Overhaul aruco marker generation (calculate svg values)

### LINKED ISSUE #115: Generate Fiducials at paper size directly
Required for #111

### PR DESCRIPTION
**Pull request by rohbotics**
This makes create_markers generate an svg at a paper size directly. It also adds a 1cm mark for measurement.

@davecrawley can you provide feedback on the new generated pdf
@jim-v Please review the change

Fixes #115 

image

### CODE REVIEW

**Comment by davecrawley** [comment]
1cm is probably not long enough. If your measurement accuracy is 1mm this will only be able to detect a defect of 10%. If you put a 20cm line then if your measurement accuracy is 1mm you will be able to detect a defect of 0.5%. Ultimately the line needs to be as long as possible while still being convenient to print. The text needs to be descriptive too something like "This line should be exactly 200mm long if it isn't fiducial localization will not work correctly - to adjust the default fiducial size edit XXXXXXX"

The only other alternative is to make the line exactly the same length as the fiducial and then say ""This line should be exactly 140mm long the exact length of the fiducial if it isn't fiducial localization will not work correctly - to adjust the default fiducial size edit param YYYY in file  XXXXXXX to this lines actual length"

Somewhat reasonable alternatives would be to make it 280mm long (2x the fiducial length). 

I would use much smaller text to fit in all the instructions and to make it unobtrusive.

Final comment - I thought we were going to do one of these lines in both the x and the y direction.

**Comment by rohbotics** [comment]
I added some red text in the output, I am not really a fan of putting a lot of instruction on the fiducial itself, as that is fairly unnecessary and repetitive to put it on every fiducial.

The lines are now the same length as the fiducial.

image
image

**Review by jim-v — APPROVED** [review]

**Comment by rohbotics** [comment]
@davecrawley Can you take another look at the generated output?

**Review by davecrawley — APPROVED** [review]
Looks awesome!

**Pull request merged**
