### PR TITLE
Added topic that enables/disables Aruco detections

### PR DESCRIPTION
**Pull request by jack-digilabs**
This allows enabling and disabling of Aruco detections to save on CPU.

### CODE REVIEW

**Comment by rohbotics** [comment]
Thanks for the PR!

Looks good, but I think the enable and disable should be a service call instead of a topic. Probably `http://docs.ros.org/api/std_srvs/html/srv/SetBool.html` would be the best choice.

**Comment by jack-digilabs** [comment]
Agreed. At the time it was easier to make it a topic but it would fit better as a service. Working on it now!

**Comment by rohbotics** [comment]
No need to close the PR, you can just modify this one.

**Comment by jack-digilabs** [comment]
Alright should be good to go  @rohbotics !

**Review by rohbotics — APPROVED** [review]

**Comment by rohbotics** [comment]
Looks good.

Thanks for the contribution!

**Pull request merged**
